services:
    db:
        # To mirror the image railway uses minus the postgis since there isn't arm compatability for it: https://docs.railway.app/databases/postgresql#image
        image: timescale/timescaledb:latest-pg17
        restart: always
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: laravel
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10
        ports:
            - 5432:5432

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy

volumes:
    pgdata:
